---
name: Math-Currency
version: 0.42
author:
  - John Peacock <jpeacock@cpan.org>
abstract: Exact Currency Math with Formatting and Rounding
license: perl
requires:
  Math::BigFloat: 1.47
provides:
  Math::Currency:
    file: lib/Math/Currency.pm
    version: 0.42
  Math::Currency::GBP:
    file: lib/Math/Currency/GBP.pm
    version: 0.41
  Math::Currency::JPY:
    file: lib/Math/Currency/JPY.pm
    version: 0.41
generated_by: Module::Build version 0.2611
